const fs = require('fs');
const file = 'c:/Users/XPRISTO/Documents/antigravity/gallant-maxwell/web/src/app/admin/page.tsx';
let code = fs.readFileSync(file, 'utf8');

const reps = [
  ['>س<', '>{language === "en" ? "A" : "س"}<'],
  ['>المدير العام<', '>{language === "en" ? "General Manager" : "المدير العام"}<'],
  ['>إدارة الفروع، الموظفين، والصلاحيات الخاصة بشبكة الصيدليات<', '>{language === "en" ? "Manage branches, staff, and permissions for the pharmacy network" : "إدارة الفروع، الموظفين، والصلاحيات الخاصة بشبكة الصيدليات"}<'],
  ['>تعديل الملف الشخصي<', '>{language === "en" ? "Edit Profile" : "تعديل الملف الشخصي"}<'],
  ['>+ فرع جديد<', '>{language === "en" ? "+ New Branch" : "+ فرع جديد"}<'],
  ['>+ موظف جديد<', '>{language === "en" ? "+ New Staff" : "+ موظف جديد"}<'],
  ['>إجمالي الفروع<', '>{language === "en" ? "Total Branches" : "إجمالي الفروع"}<'],
  ['>فروع نشطة<', '>{language === "en" ? "Active Branches" : "فروع نشطة"}<'],
  ['>إجمالي الموظفين<', '>{language === "en" ? "Total Staff" : "إجمالي الموظفين"}<'],
  ['>صيادلة<', '>{language === "en" ? "Pharmacists" : "صيادلة"}<'],
  ['>الحسابات والديون<', '>{language === "en" ? "Accounts & Debts" : "الحسابات والديون"}<'],
  ['>₪ للموردين<', '>{language === "en" ? "₪ for Suppliers" : "₪ للموردين"}<'],
  ['>إدارة الفروع<', '>{language === "en" ? "Manage Branches" : "إدارة الفروع"}<'],
  ['>الموظفون<', '>{language === "en" ? "Staff" : "الموظفون"}<'],
  ['>التقارير المالية 📊<', '>{language === "en" ? "Financial Reports 📊" : "التقارير المالية 📊"}<'],
  ['>إعدادات النظام ⚙️<', '>{language === "en" ? "System Settings ⚙️" : "إعدادات النظام ⚙️"}<'],
  ['>الاشتراك والفواتير 💳<', '>{language === "en" ? "Subscription & Billing 💳" : "الاشتراك والفواتير 💳"}<'],
  ['>رقم الفرع<', '>{language === "en" ? "Branch Number" : "رقم الفرع"}<'],
  ['>اسم الفرع<', '>{language === "en" ? "Branch Name" : "اسم الفرع"}<'],
  ['>المدير المسؤول<', '>{language === "en" ? "Manager in Charge" : "المدير المسؤول"}<'],
  ['>عدد الموظفين<', '>{language === "en" ? "Number of Staff" : "عدد الموظفين"}<'],
  ['>الحالة<', '>{language === "en" ? "Status" : "الحالة"}<'],
  ['>يعمل<', '>{language === "en" ? "Active" : "يعمل"}<'],
  ['>قيد التجهيز<', '>{language === "en" ? "Preparing" : "قيد التجهيز"}<'],
  ['>الرقم الوظيفي<', '>{language === "en" ? "Employee ID" : "الرقم الوظيفي"}<'],
  ['>اسم الموظف<', '>{language === "en" ? "Employee Name" : "اسم الموظف"}<'],
  ['>المسمى الوظيفي<', '>{language === "en" ? "Job Title" : "المسمى الوظيفي"}<'],
  ['>الفرع التابع له<', '>{language === "en" ? "Branch" : "الفرع التابع له"}<'],
  ['>الراتب الأساسي<', '>{language === "en" ? "Basic Salary" : "الراتب الأساسي"}<'],
  ['>إجراءات<', '>{language === "en" ? "Actions" : "إجراءات"}<'],
  ['>على رأس العمل<', '>{language === "en" ? "On Duty" : "على رأس العمل"}<'],
  ['>موقوف<', '>{language === "en" ? "Suspended" : "موقوف"}<'],
  ['>إجازة<', '>{language === "en" ? "On Leave" : "إجازة"}<'],
  ['>تعديل<', '>{language === "en" ? "Edit" : "تعديل"}<'],
  ['>توقيف<', '>{language === "en" ? "Suspend" : "توقيف"}<'],
  ['>تفعيل<', '>{language === "en" ? "Activate" : "تفعيل"}<'],
  ['>فصل<', '>{language === "en" ? "Fire" : "فصل"}<'],
  ['>التقارير المالية والأرباح<', '>{language === "en" ? "Financial Reports and Profits" : "التقارير المالية والأرباح"}<'],
  ['>تحكم في المعادلات المالية واطّلع على صافي الأرباح اليومية.<', '>{language === "en" ? "Control financial formulas and view daily net profits." : "تحكم في المعادلات المالية واطّلع على صافي الأرباح اليومية."}<'],
  ['>تضمين رواتب الموظفين في حساب المصروفات؟<', '>{language === "en" ? "Include staff salaries in expenses calculation?" : "تضمين رواتب الموظفين في حساب المصروفات؟"}<'],
  ['>المبيعات اليومية 🟢<', '>{language === "en" ? "Daily Sales 🟢" : "المبيعات اليومية 🟢"}<'],
  ['>تكلفة البضاعة المباعة 🔴<', '>{language === "en" ? "Cost of Goods Sold 🔴" : "تكلفة البضاعة المباعة 🔴"}<'],
  ['>مصروفات أخرى 🔴<', '>{language === "en" ? "Other Expenses 🔴" : "مصروفات أخرى 🔴"}<'],
  ['>+ إضافة مصروف<', '>{language === "en" ? "+ Add Expense" : "+ إضافة مصروف"}<'],
  ['>معادلة الحساب: المبيعات - تكلفة البضاعة - المصروفات<', '>{language === "en" ? "Calculation Formula: Sales - Cost of Goods Sold - Expenses" : "معادلة الحساب: المبيعات - تكلفة البضاعة - المصروفات"}<'],
  ['>السياسات المالية والصلاحيات (تطبق على جميع الفروع)<', '>{language === "en" ? "Financial Policies and Permissions (Apply to all branches)" : "السياسات المالية والصلاحيات (تطبق على جميع الفروع)"}<'],
  ['>الحد الأقصى للخصم للكاشير (%)<', '>{language === "en" ? "Maximum Discount for Cashier (%)" : "الحد الأقصى للخصم للكاشير (%)"}<'],
  ['>الحد الأقصى للخصم لمدير الفرع (%)<', '>{language === "en" ? "Maximum Discount for Branch Manager (%)" : "الحد الأقصى للخصم لمدير الفرع (%)"}<'],
  ['>المدة المسموحة للإرجاع (بالأيام)<', '>{language === "en" ? "Allowed Return Period (in days)" : "المدة المسموحة للإرجاع (بالأيام)"}<'],
  ['>تفعيل تنبيهات نواقص المخزون المركزية<', '>{language === "en" ? "Enable Central Inventory Shortage Alerts" : "تفعيل تنبيهات نواقص المخزون المركزية"}<'],
  ['>حفظ الإعدادات<', '>{language === "en" ? "Save Settings" : "حفظ الإعدادات"}<'],
  ['>الاشتراك السنوي (Premium)<', '>{language === "en" ? "Annual Subscription (Premium)" : "الاشتراك السنوي (Premium)"}<'],
  ['>يسمح لك بإدارة حتى 5 فروع مع تقارير متقدمة.<', '>{language === "en" ? "Allows you to manage up to 5 branches with advanced reports." : "يسمح لك بإدارة حتى 5 فروع مع تقارير متقدمة."}<'],
  ['>الفروع المستخدمة<', '>{language === "en" ? "Used Branches" : "الفروع المستخدمة"}<'],
  ['>تاريخ التجديد القادم<', '>{language === "en" ? "Next Renewal Date" : "تاريخ التجديد القادم"}<'],
  ['>ترقية الباقة (فروع أكثر)<', '>{language === "en" ? "Upgrade Plan (More Branches)" : "ترقية الباقة (فروع أكثر)"}<'],
  ['>تحميل فواتير الاشتراك<', '>{language === "en" ? "Download Subscription Invoices" : "تحميل فواتير الاشتراك"}<'],
  ['>بيانات الدخول للموظفين<', '>{language === "en" ? "Staff Login Credentials" : "بيانات الدخول للموظفين"}<'],
  ['>بيانات سرية 🔒<', '>{language === "en" ? "Confidential Data 🔒" : "بيانات سرية 🔒"}<'],
  ['>كلمة المرور<', '>{language === "en" ? "Password" : "كلمة المرور"}<'],
  ['>تعديل البيانات<', '>{language === "en" ? "Edit Data" : "تعديل البيانات"}<'],
  ['>إضافة مصروف جديد<', '>{language === "en" ? "Add New Expense" : "إضافة مصروف جديد"}<'],
  ['>نوع المصروف<', '>{language === "en" ? "Expense Type" : "نوع المصروف"}<'],
  ['>نثريات (ضيافة، تنظيف...)<', '>{language === "en" ? "Sundries (Hospitality, Cleaning...)" : "نثريات (ضيافة، تنظيف...)"}<'],
  ['>فواتير (كهرباء، ماء، إنترنت)<', '>{language === "en" ? "Bills (Electricity, Water, Internet)" : "فواتير (كهرباء، ماء، إنترنت)"}<'],
  ['>صيانة وإصلاحات<', '>{language === "en" ? "Maintenance & Repairs" : "صيانة وإصلاحات"}<'],
  ['>أخرى<', '>{language === "en" ? "Other" : "أخرى"}<'],
  ['>وصف المصروف<', '>{language === "en" ? "Expense Description" : "وصف المصروف"}<'],
  ['>المبلغ (₪)<', '>{language === "en" ? "Amount (₪)" : "المبلغ (₪)"}<'],
  ['>التاريخ<', '>{language === "en" ? "Date" : "التاريخ"}<'],
  ['>إلغاء<', '>{language === "en" ? "Cancel" : "إلغاء"}<'],
  ['>حفظ المصروف<', '>{language === "en" ? "Save Expense" : "حفظ المصروف"}<'],
  ['>تعديل بيانات الموظف<', '>{language === "en" ? "Edit Staff Data" : "تعديل بيانات الموظف"}<'],
  ['>إضافة موظف جديد<', '>{language === "en" ? "Add New Staff" : "إضافة موظف جديد"}<'],
  ['>صيدلي / كاشير<', '>{language === "en" ? "Pharmacist / Cashier" : "صيدلي / كاشير"}<'],
  ['>مدير فرع<', '>{language === "en" ? "Branch Manager" : "مدير فرع"}<'],
  ['>مساعد صيدلي<', '>{language === "en" ? "Pharmacy Assistant" : "مساعد صيدلي"}<'],
  ['>مستودع<', '>{language === "en" ? "Warehouse" : "مستودع"}<'],
  ['>اختر الفرع...<', '>{language === "en" ? "Select Branch..." : "اختر الفرع..."}<'],
  ['>رقم الجوال<', '>{language === "en" ? "Mobile Number" : "رقم الجوال"}<'],
  ['>اسم المستخدم (للدخول)<', '>{language === "en" ? "Username (for login)" : "اسم المستخدم (للدخول)"}<'],
  ['>تأكيد فصل الموظف<', '>{language === "en" ? "Confirm Staff Firing" : "تأكيد فصل الموظف"}<'],
  ['>هل أنت متأكد من رغبتك في فصل الموظف <', '>{language === "en" ? "Are you sure you want to fire the staff member " : "هل أنت متأكد من رغبتك في فصل الموظف "}<'],
  ['> نهائياً من النظام؟<', '>{language === "en" ? " permanently from the system?" : " نهائياً من النظام؟"}<'],
  ['>نعم، تأكيد الفصل<', '>{language === "en" ? "Yes, Confirm Firing" : "نعم، تأكيد الفصل"}<'],
  ['>تراجع<', '>{language === "en" ? "Back" : "تراجع"}<'],
  ['>تعديل الملف الشخصي للإدارة<', '>{language === "en" ? "Edit Admin Profile" : "تعديل الملف الشخصي للإدارة"}<'],
  ['>الاسم بالكامل<', '>{language === "en" ? "Full Name" : "الاسم بالكامل"}<'],
  ['>البريد الإلكتروني (اسم المستخدم)<', '>{language === "en" ? "Email (Username)" : "البريد الإلكتروني (اسم المستخدم)"}<'],
  ['>تغيير كلمة المرور<', '>{language === "en" ? "Change Password" : "تغيير كلمة المرور"}<'],
  ['>كلمة المرور الحالية<', '>{language === "en" ? "Current Password" : "كلمة المرور الحالية"}<'],
  ['>كلمة المرور الجديدة<', '>{language === "en" ? "New Password" : "كلمة المرور الجديدة"}<'],
  ['>تأكيد الكلمة الجديدة<', '>{language === "en" ? "Confirm New Password" : "تأكيد الكلمة الجديدة"}<'],
  ['>إضافة فرع جديد<', '>{language === "en" ? "Add New Branch" : "إضافة فرع جديد"}<'],
  ['>اسم الفرع / المنطقة<', '>{language === "en" ? "Branch Name / Area" : "اسم الفرع / المنطقة"}<'],
  ['>المدير المسؤول عن الفرع<', '>{language === "en" ? "Manager in Charge of Branch" : "المدير المسؤول عن الفرع"}<'],
  ['>حالة الفرع المبدئية<', '>{language === "en" ? "Initial Branch Status" : "حالة الفرع المبدئية"}<'],
  ['>حفظ وإضافة<', '>{language === "en" ? "Save and Add" : "حفظ وإضافة"}<']
];

reps.forEach(([k,v]) => {
  // Try to replace text ignoring leading/trailing whitespaces roughly
  let regex = new RegExp(k.replace('>', '>\\s*').replace('<', '\\s*<'), 'g');
  code = code.replace(regex, v);
});

fs.writeFileSync(file, code, 'utf8');
