const fs = require('fs');
const file = 'c:/Users/XPRISTO/Documents/antigravity/gallant-maxwell/web/src/app/admin/page.tsx';
let code = fs.readFileSync(file, 'utf8');

// 1. Inject language
if (!code.includes('const language = useStore')) {
  code = code.replace(
    'const user = useStore((state) => state.user);',
    'const user = useStore((state: any) => state.user);\n  const language = useStore((state: any) => state.language);'
  );
  code = code.replace('[user, router]);', '[user, router, language]);');
}

const replacements = {
  '"ليس لديك الصلاحية للوصول إلى هذه الصفحة"': 'language === "en" ? "You do not have permission to access this page" : "ليس لديك الصلاحية للوصول إلى هذه الصفحة"',
  '>س<': '>{language === "en" ? "A" : "س"}<',
  'أهلاً بك،': '{language === "en" ? "Welcome, " : "أهلاً بك، "}',
  '"المدير العام"': 'language === "en" ? "General Manager" : "المدير العام"',
  '>المدير العام<': '>{language === "en" ? "General Manager" : "المدير العام"}<',
  '>إدارة الفروع، الموظفين، والصلاحيات الخاصة بشبكة الصيدليات<': '>{language === "en" ? "Manage branches, staff, and permissions for the pharmacy network" : "إدارة الفروع، الموظفين، والصلاحيات الخاصة بشبكة الصيدليات"}<',
  '>تعديل الملف الشخصي<': '>{language === "en" ? "Edit Profile" : "تعديل الملف الشخصي"}<',
  '>+ فرع جديد<': '>{language === "en" ? "+ New Branch" : "+ فرع جديد"}<',
  '>+ موظف جديد<': '>{language === "en" ? "+ New Staff" : "+ موظف جديد"}<',
  '>إجمالي الفروع<': '>{language === "en" ? "Total Branches" : "إجمالي الفروع"}<',
  '>فروع نشطة<': '>{language === "en" ? "Active Branches" : "فروع نشطة"}<',
  '>إجمالي الموظفين<': '>{language === "en" ? "Total Staff" : "إجمالي الموظفين"}<',
  '>صيادلة<': '>{language === "en" ? "Pharmacists" : "صيادلة"}<',
  '>الحسابات والديون<': '>{language === "en" ? "Accounts & Debts" : "الحسابات والديون"}<',
  '>₪ للموردين<': '>{language === "en" ? "₪ for Suppliers" : "₪ للموردين"}<',
  '>إدارة الفروع<': '>{language === "en" ? "Manage Branches" : "إدارة الفروع"}<',
  '>الموظفون<': '>{language === "en" ? "Staff" : "الموظفون"}<',
  '>التقارير المالية 📊<': '>{language === "en" ? "Financial Reports 📊" : "التقارير المالية 📊"}<',
  '>إعدادات النظام ⚙️<': '>{language === "en" ? "System Settings ⚙️" : "إعدادات النظام ⚙️"}<',
  '>الاشتراك والفواتير 💳<': '>{language === "en" ? "Subscription & Billing 💳" : "الاشتراك والفواتير 💳"}<',
  '"ابحث عن فرع..."': 'language === "en" ? "Search for branch..." : "ابحث عن فرع..."',
  '"ابحث عن موظف..."': 'language === "en" ? "Search for staff..." : "ابحث عن موظف..."',
  '>رقم الفرع<': '>{language === "en" ? "Branch Number" : "رقم الفرع"}<',
  '>اسم الفرع<': '>{language === "en" ? "Branch Name" : "اسم الفرع"}<',
  '>المدير المسؤول<': '>{language === "en" ? "Manager in Charge" : "المدير المسؤول"}<',
  '>عدد الموظفين<': '>{language === "en" ? "Number of Staff" : "عدد الموظفين"}<',
  '>الحالة<': '>{language === "en" ? "Status" : "الحالة"}<',
  'br.staffCount} صيادلة': 'br.staffCount} {language === "en" ? "Pharmacists" : "صيادلة"}',
  '>يعمل<': '>{language === "en" ? "Active" : "يعمل"}<',
  '>قيد التجهيز<': '>{language === "en" ? "Preparing" : "قيد التجهيز"}<',
  '>الرقم الوظيفي<': '>{language === "en" ? "Employee ID" : "الرقم الوظيفي"}<',
  '>اسم الموظف<': '>{language === "en" ? "Employee Name" : "اسم الموظف"}<',
  '>المسمى الوظيفي<': '>{language === "en" ? "Job Title" : "المسمى الوظيفي"}<',
  '>الفرع التابع له<': '>{language === "en" ? "Branch" : "الفرع التابع له"}<',
  '>الراتب الأساسي<': '>{language === "en" ? "Basic Salary" : "الراتب الأساسي"}<',
  '>إجراءات<': '>{language === "en" ? "Actions" : "إجراءات"}<',
  '>على رأس العمل<': '>{language === "en" ? "On Duty" : "على رأس العمل"}<',
  '>موقوف<': '>{language === "en" ? "Suspended" : "موقوف"}<',
  '>إجازة<': '>{language === "en" ? "On Leave" : "إجازة"}<',
  '>تعديل<': '>{language === "en" ? "Edit" : "تعديل"}<',
  '>توقيف<': '>{language === "en" ? "Suspend" : "توقيف"}<',
  '>تفعيل<': '>{language === "en" ? "Activate" : "تفعيل"}<',
  '>فصل<': '>{language === "en" ? "Fire" : "فصل"}<',
  '"تم إيقاف الموظف مؤقتاً"': 'language === "en" ? "Staff member temporarily suspended" : "تم إيقاف الموظف مؤقتاً"',
  '"تم إعادة الموظف للعمل"': 'language === "en" ? "Staff member reinstated" : "تم إعادة الموظف للعمل"',
  '>التقارير المالية والأرباح<': '>{language === "en" ? "Financial Reports and Profits" : "التقارير المالية والأرباح"}<',
  '>تحكم في المعادلات المالية واطّلع على صافي الأرباح اليومية.<': '>{language === "en" ? "Control financial formulas and view daily net profits." : "تحكم في المعادلات المالية واطّلع على صافي الأرباح اليومية."}<',
  '>تضمين رواتب الموظفين في حساب المصروفات؟<': '>{language === "en" ? "Include staff salaries in expenses calculation?" : "تضمين رواتب الموظفين في حساب المصروفات؟"}<',
  '>المبيعات اليومية 🟢<': '>{language === "en" ? "Daily Sales 🟢" : "المبيعات اليومية 🟢"}<',
  '>تكلفة البضاعة المباعة 🔴<': '>{language === "en" ? "Cost of Goods Sold 🔴" : "تكلفة البضاعة المباعة 🔴"}<',
  '>مصروفات أخرى 🔴<': '>{language === "en" ? "Other Expenses 🔴" : "مصروفات أخرى 🔴"}<',
  '>+ إضافة مصروف<': '>{language === "en" ? "+ Add Expense" : "+ إضافة مصروف"}<',
  '>الرواتب (يومي) {includeSalaries ? "🔴" : "⚪"}<': '>{language === "en" ? "Salaries (Daily)" : "الرواتب (يومي)"} {includeSalaries ? "🔴" : "⚪"}<',
  '"الربح الصافي (Net Profit)"': 'language === "en" ? "Net Profit" : "الربح الصافي (Net Profit)"',
  '"الربح التشغيلي (Gross Profit)"': 'language === "en" ? "Gross Profit" : "الربح التشغيلي (Gross Profit)"',
  '>معادلة الحساب: المبيعات - تكلفة البضاعة - المصروفات<': '>{language === "en" ? "Calculation Formula: Sales - Cost of Goods Sold - Expenses" : "معادلة الحساب: المبيعات - تكلفة البضاعة - المصروفات"}<',
  '"- الرواتب"': 'language === "en" ? " - Salaries" : "- الرواتب"',
  '>السياسات المالية والصلاحيات (تطبق على جميع الفروع)<': '>{language === "en" ? "Financial Policies and Permissions (Apply to all branches)" : "السياسات المالية والصلاحيات (تطبق على جميع الفروع)"}<',
  '>الحد الأقصى للخصم للكاشير (%)<': '>{language === "en" ? "Maximum Discount for Cashier (%)" : "الحد الأقصى للخصم للكاشير (%)"}<',
  '>الحد الأقصى للخصم لمدير الفرع (%)<': '>{language === "en" ? "Maximum Discount for Branch Manager (%)" : "الحد الأقصى للخصم لمدير الفرع (%)"}<',
  '>المدة المسموحة للإرجاع (بالأيام)<': '>{language === "en" ? "Allowed Return Period (in days)" : "المدة المسموحة للإرجاع (بالأيام)"}<',
  '>تفعيل تنبيهات نواقص المخزون المركزية<': '>{language === "en" ? "Enable Central Inventory Shortage Alerts" : "تفعيل تنبيهات نواقص المخزون المركزية"}<',
  '>حفظ الإعدادات<': '>{language === "en" ? "Save Settings" : "حفظ الإعدادات"}<',
  '>الاشتراك السنوي (Premium)<': '>{language === "en" ? "Annual Subscription (Premium)" : "الاشتراك السنوي (Premium)"}<',
  '>يسمح لك بإدارة حتى 5 فروع مع تقارير متقدمة.<': '>{language === "en" ? "Allows you to manage up to 5 branches with advanced reports." : "يسمح لك بإدارة حتى 5 فروع مع تقارير متقدمة."}<',
  '>الفروع المستخدمة<': '>{language === "en" ? "Used Branches" : "الفروع المستخدمة"}<',
  '>تاريخ التجديد القادم<': '>{language === "en" ? "Next Renewal Date" : "تاريخ التجديد القادم"}<',
  '>ترقية الباقة (فروع أكثر)<': '>{language === "en" ? "Upgrade Plan (More Branches)" : "ترقية الباقة (فروع أكثر)"}<',
  '>تحميل فواتير الاشتراك<': '>{language === "en" ? "Download Subscription Invoices" : "تحميل فواتير الاشتراك"}<',
  '>بيانات الدخول للموظفين<': '>{language === "en" ? "Staff Login Credentials" : "بيانات الدخول للموظفين"}<',
  '>بيانات سرية 🔒<': '>{language === "en" ? "Confidential Data 🔒" : "بيانات سرية 🔒"}<',
  '>كلمة المرور<': '>{language === "en" ? "Password" : "كلمة المرور"}<',
  '>تعديل البيانات<': '>{language === "en" ? "Edit Data" : "تعديل البيانات"}<',
  '>إضافة مصروف جديد<': '>{language === "en" ? "Add New Expense" : "إضافة مصروف جديد"}<',
  '>نوع المصروف<': '>{language === "en" ? "Expense Type" : "نوع المصروف"}<',
  '>نثريات (ضيافة، تنظيف...)<': '>{language === "en" ? "Sundries (Hospitality, Cleaning...)" : "نثريات (ضيافة، تنظيف...)"}<',
  '>فواتير (كهرباء، ماء، إنترنت)<': '>{language === "en" ? "Bills (Electricity, Water, Internet)" : "فواتير (كهرباء، ماء، إنترنت)"}<',
  '>صيانة وإصلاحات<': '>{language === "en" ? "Maintenance & Repairs" : "صيانة وإصلاحات"}<',
  '>أخرى<': '>{language === "en" ? "Other" : "أخرى"}<',
  '>وصف المصروف<': '>{language === "en" ? "Expense Description" : "وصف المصروف"}<',
  '"مثال: فاتورة كهرباء شهر ٨"': 'language === "en" ? "Example: August electricity bill" : "مثال: فاتورة كهرباء شهر ٨"',
  '>المبلغ (₪)<': '>{language === "en" ? "Amount (₪)" : "المبلغ (₪)"}<',
  '>التاريخ<': '>{language === "en" ? "Date" : "التاريخ"}<',
  '>إلغاء<': '>{language === "en" ? "Cancel" : "إلغاء"}<',
  '"يرجى تعبئة الحقول"': 'language === "en" ? "Please fill in all fields" : "يرجى تعبئة الحقول"',
  '"تم تسجيل المصروف بنجاح"': 'language === "en" ? "Expense recorded successfully" : "تم تسجيل المصروف بنجاح"',
  '>حفظ المصروف<': '>{language === "en" ? "Save Expense" : "حفظ المصروف"}<',
  '>تعديل بيانات الموظف<': '>{language === "en" ? "Edit Staff Data" : "تعديل بيانات الموظف"}<',
  '>إضافة موظف جديد<': '>{language === "en" ? "Add New Staff" : "إضافة موظف جديد"}<',
  '"الاسم الرباعي"': 'language === "en" ? "Full Name" : "الاسم الرباعي"',
  '"صيدلي / كاشير"': 'language === "en" ? "Pharmacist / Cashier" : "صيدلي / كاشير"',
  '>صيدلي / كاشير<': '>{language === "en" ? "Pharmacist / Cashier" : "صيدلي / كاشير"}<',
  '>مدير فرع<': '>{language === "en" ? "Branch Manager" : "مدير فرع"}<',
  '>مساعد صيدلي<': '>{language === "en" ? "Pharmacy Assistant" : "مساعد صيدلي"}<',
  '>مستودع<': '>{language === "en" ? "Warehouse" : "مستودع"}<',
  '>اختر الفرع...<': '>{language === "en" ? "Select Branch..." : "اختر الفرع..."}<',
  '"مثال: 1500"': 'language === "en" ? "Example: 1500" : "مثال: 1500"',
  '>رقم الجوال<': '>{language === "en" ? "Mobile Number" : "رقم الجوال"}<',
  '>اسم المستخدم (للدخول)<': '>{language === "en" ? "Username (for login)" : "اسم المستخدم (للدخول)"}<',
  '"إخفاء كلمة المرور"': 'language === "en" ? "Hide Password" : "إخفاء كلمة المرور"',
  '"إظهار كلمة المرور"': 'language === "en" ? "Show Password" : "إظهار كلمة المرور"',
  '"تم تحديث بيانات الموظف بنجاح!"': 'language === "en" ? "Staff data updated successfully!" : "تم تحديث بيانات الموظف بنجاح!"',
  '"حدث خطأ أثناء التحديث"': 'language === "en" ? "Error during update" : "حدث خطأ أثناء التحديث"',
  '"تعذر الاتصال بالخادم"': 'language === "en" ? "Could not connect to server" : "تعذر الاتصال بالخادم"',
  '"تم إضافة الموظف الجديد بنجاح!"': 'language === "en" ? "New staff added successfully!" : "تم إضافة الموظف الجديد بنجاح!"',
  '"حدث خطأ أثناء الإضافة"': 'language === "en" ? "Error during addition" : "حدث خطأ أثناء الإضافة"',
  '"حفظ التعديلات"': 'language === "en" ? "Save Changes" : "حفظ التعديلات"',
  '"تعيين الموظف"': 'language === "en" ? "Appoint Staff" : "تعيين الموظف"',
  '>تأكيد فصل الموظف<': '>{language === "en" ? "Confirm Staff Firing" : "تأكيد فصل الموظف"}<',
  '>هل أنت متأكد من رغبتك في فصل الموظف <': '>{language === "en" ? "Are you sure you want to fire the staff member " : "هل أنت متأكد من رغبتك في فصل الموظف "}<',
  '> نهائياً من النظام؟<': '>{language === "en" ? " permanently from the system?" : " نهائياً من النظام؟"}<',
  '"تم!"': 'language === "en" ? "Done!" : "تم!"',
  '>نعم، تأكيد الفصل<': '>{language === "en" ? "Yes, Confirm Firing" : "نعم، تأكيد الفصل"}<',
  '>تراجع<': '>{language === "en" ? "Back" : "تراجع"}<',
  '>تعديل الملف الشخصي للإدارة<': '>{language === "en" ? "Edit Admin Profile" : "تعديل الملف الشخصي للإدارة"}<',
  '>الاسم بالكامل<': '>{language === "en" ? "Full Name" : "الاسم بالكامل"}<',
  '>البريد الإلكتروني (اسم المستخدم)<': '>{language === "en" ? "Email (Username)" : "البريد الإلكتروني (اسم المستخدم)"}<',
  '>تغيير كلمة المرور<': '>{language === "en" ? "Change Password" : "تغيير كلمة المرور"}<',
  '>كلمة المرور الحالية<': '>{language === "en" ? "Current Password" : "كلمة المرور الحالية"}<',
  '>كلمة المرور الجديدة<': '>{language === "en" ? "New Password" : "كلمة المرور الجديدة"}<',
  '>تأكيد الكلمة الجديدة<': '>{language === "en" ? "Confirm New Password" : "تأكيد الكلمة الجديدة"}<',
  '"تم حفظ تعديلات الملف الشخصي بنجاح!"': 'language === "en" ? "Profile changes saved successfully!" : "تم حفظ تعديلات الملف الشخصي بنجاح!"',
  '>إضافة فرع جديد<': '>{language === "en" ? "Add New Branch" : "إضافة فرع جديد"}<',
  '>اسم الفرع / المنطقة<': '>{language === "en" ? "Branch Name / Area" : "اسم الفرع / المنطقة"}<',
  '"مثال: فرع النصيرات"': 'language === "en" ? "Example: Nuseirat Branch" : "مثال: فرع النصيرات"',
  '>المدير المسؤول عن الفرع<': '>{language === "en" ? "Manager in Charge of Branch" : "المدير المسؤول عن الفرع"}<',
  '"اسم الصيدلي"': 'language === "en" ? "Pharmacist Name" : "اسم الصيدلي"',
  '>حالة الفرع المبدئية<': '>{language === "en" ? "Initial Branch Status" : "حالة الفرع المبدئية"}<',
  '"يرجى تعبئة بيانات الفرع"': 'language === "en" ? "Please fill in branch details" : "يرجى تعبئة بيانات الفرع"',
  '>حفظ وإضافة<': '>{language === "en" ? "Save and Add" : "حفظ وإضافة"}<',
  '"نثريات"': 'language === "en" ? "Sundries" : "نثريات"',
  'editingStaff ? "تعديل بيانات الموظف" : "إضافة موظف جديد"': 'editingStaff ? (language === "en" ? "Edit Staff Data" : "تعديل بيانات الموظف") : (language === "en" ? "Add New Staff" : "إضافة موظف جديد")',
  'editingStaff?.id ? "حفظ التعديلات" : "تعيين الموظف"': 'editingStaff?.id ? (language === "en" ? "Save Changes" : "حفظ التعديلات") : (language === "en" ? "Appoint Staff" : "تعيين الموظف")',
  'br.status === "active" ? "يعمل" : "قيد التجهيز"': 'br.status === "active" ? (language === "en" ? "Active" : "يعمل") : (language === "en" ? "Preparing" : "قيد التجهيز")',
  'st.status === "active" ? "على رأس العمل" : st.status === "suspended" ? "موقوف" : "إجازة"': 'st.status === "active" ? (language === "en" ? "On Duty" : "على رأس العمل") : st.status === "suspended" ? (language === "en" ? "Suspended" : "موقوف") : (language === "en" ? "On Leave" : "إجازة")',
  'st.status === "active" ? "توقيف" : "تفعيل"': 'st.status === "active" ? (language === "en" ? "Suspend" : "توقيف") : (language === "en" ? "Activate" : "تفعيل")',
  'newStatus === "suspended" ? "تم إيقاف الموظف مؤقتاً" : "تم إعادة الموظف للعمل"': 'newStatus === "suspended" ? (language === "en" ? "Staff member temporarily suspended" : "تم إيقاف الموظف مؤقتاً") : (language === "en" ? "Staff member reinstated" : "تم إعادة الموظف للعمل")'
};

for (const [key, value] of Object.entries(replacements)) {
  code = code.split(key).join(value);
}

// Any missed Arabic text...
code = code.replace(
  '{language === "en" ? "Welcome, " : "أهلاً بك، "}{(user as any)?.name || user?.username || (language === "en" ? "General Manager" : "المدير العام")} 👋',
  '{language === "en" ? "Welcome, " : "أهلاً بك، "}{(user as any)?.name || user?.username || (language === "en" ? "General Manager" : "المدير العام")} 👋'
);

fs.writeFileSync(file, code, 'utf8');
